# -*- coding: utf-8 -*-
"""Textos de ayuda del panel del consejo, en español e inglés (D110). Los usa ayuda_tarjetas.py.

TARJETAS: una entrada por cada elemento marcado data-ayuda="<clave>" en el panel completo o en el movil, con
  "es" y "en": titulo, que (qué muestra), leer (cómo leerla: escalas, colores, signos; opcional), porque (por qué
  importa) y donde (dónde se explica en SEVEN-G; opcional); y "columnas": las columnas o recuadros que la tarjeta
  muestra, por su rótulo en el panel (clave de COLUMNAS) o con una explicación propia {"c": rótulo, "es", "en"}.
COLUMNAS: qué significa cada columna o recuadro, por su rótulo tal como lo escribe el panel (en español). Una clave
  que termina en «…» vale para todo rótulo que empiece igual («Estimación …» → «Estimación consejo asesor»).
  "en" es [nombre en inglés, explicación]. El panel pone esta explicación como tooltip en cada encabezado de tabla
  y en cada rótulo de recuadro, también en las fichas; dentro de una tarjeta manda la explicación propia de la tarjeta.
Los textos son HTML de confianza. Una columna o tarjeta nueva del panel necesita su entrada aquí, en los dos idiomas
(verificar_coherencia.ps1, sección 23).
"""


def c(es, en_nombre, en):
    return {"es": es, "en": [en_nombre, en]}


def propia(rotulo, es, en_nombre, en):
    return {"c": rotulo, "es": es, "en": [en_nombre, en]}


COLUMNAS = {
    # ---- identificación del caso
    "ID": c("Código del caso en el registro de iniciativas T01 (IA-AAAA-NNN).", "ID", "Code of the case in the T01 initiative register (IA-YYYY-NNN)."),
    "Caso": c("Nombre del caso de uso de IA. Al pulsarlo se abre su ficha.", "Case", "Name of the AI use case. Clicking it opens its record."),
    "Qué es y para qué se usa": c("Descripción breve del caso en lenguaje de negocio.", "What it is and what it is used for", "Short description of the case in business language."),
    "Compañía": c("Sociedad del grupo que es dueña del caso.", "Company", "Group company that owns the case."),
    "Unidad": c("Unidad de negocio o área que usa el caso y responde de su beneficio.", "Unit", "Business unit or area that uses the case and is accountable for its benefit."),
    "Unidad de negocio": c("Unidad que usa la iniciativa transversal; «Común» recoge el coste que no se reparte.", "Business unit", "Unit using the cross-cutting initiative; «Common» holds the cost that is not allocated."),
    "Tecnología": c("Tipo de IA: analítica o predictiva, generativa, agéntica, visión, etc.", "Technology", "Type of AI: analytical or predictive, generative, agentic, vision, etc."),
    "Estado": c("Etapa del embudo en la que está el caso: Propuesto, Hipótesis de valor, POC, En desarrollo, En uso, o una salida (No aprobado, Descartado, Desenganchado).", "Status", "Funnel stage the case is in: Proposed, Value hypothesis, POC, In development, In use, or an exit (Not approved, Discarded, Disengaged)."),
    "Complejidad": c("Complejidad declarada del caso (baja, media, alta); decide el límite de días en desarrollo.", "Complexity", "Declared complexity of the case (low, medium, high); it sets the day limit in development."),
    "Puesta en producción": c("Fecha en que el caso empezó a usarse de verdad; si solo hay año, es una estimación.", "Go-live", "Date on which the case actually started being used; if only a year is shown, it is an estimate."),
    "Reglamento IA …": c("Clasificación según el Reglamento (UE) de IA: prohibido, alto riesgo, transparencia, riesgo mínimo o fuera de ámbito. Entre paréntesis, de quién es la clasificación.", "AI Act …", "Classification under the EU AI Act: prohibited, high risk, transparency, minimal risk or out of scope. In brackets, who made the classification."),
    "Controles": c("Controles obligatorios hechos o no aplicables sobre el total (clasificación, derechos fundamentales, protección de datos, seguridad, manual de uso y riesgo de ataques con IA).", "Controls", "Mandatory controls done or not applicable out of the total (classification, fundamental rights, data protection, security, user manual and AI-attack risk)."),
    "Fuente": c("De dónde sale el dato: registro T01, declarado por la compañía o estimado por el consejo asesor.", "Source", "Where the figure comes from: T01 register, declared by the company or estimated by the advisory board."),
    "Δ neto …": c("Cambio del neto anual frente a la foto elegida en «Comparar con»; vacío si no se ha elegido ninguna.", "Δ net …", "Change in annual net against the snapshot chosen in «Compare with»; empty if none is chosen."),
    "Dato del valor": c("Calidad del dato de valor: validado (comprobado por Control de Gestión), declarado (lo dice la compañía), estimado (lo calcula el consejo asesor) o sin dato.", "Value data", "Quality of the value figure: validated (checked by Management Control), declared (stated by the company), estimated (calculated by the advisory board) or no data."),
    # ---- economía
    "Construcción": c("Inversión única para construir el caso (desarrollo, integración, datos). No se repite cada año.", "Build", "One-off investment to build the case (development, integration, data). It does not recur every year."),
    "Inversión": c("Inversión única del caso (construcción y, si la hay, la adicional prevista).", "Investment", "One-off investment of the case (build and, if any, the planned additional investment)."),
    "Inversión de construcción": c("Suma de lo invertido una vez para construir los casos seleccionados.", "Build investment", "Sum of what was invested once to build the selected cases."),
    "Coste anual": c("Coste recurrente de cada año: licencias, consumo de modelos, nube, soporte, personas dedicadas y mantenimiento.", "Annual cost", "Recurring cost each year: licences, model consumption, cloud, support, dedicated staff and maintenance."),
    "Coste estimado": c("Casos cuyo coste no ha dado la compañía y lo ha estimado el consejo asesor.", "Estimated cost", "Cases whose cost the company has not provided and the advisory board has estimated."),
    "Costes": c("Coste recurrente anual.", "Costs", "Recurring annual cost."),
    "− Costes": c("Se resta el coste recurrente anual.", "− Costs", "The recurring annual cost is subtracted."),
    "Eficiencias": c("Ahorro real ya materializado en la cuenta de resultados (menos coste, menos horas pagadas), en euros al año.", "Efficiencies", "Real savings already materialised in the P&amp;L (lower cost, fewer paid hours), in euros per year."),
    "Eficiencias materializadas": c("Ahorro real que ya se nota en el coste, en euros al año.", "Materialised efficiencies", "Real savings already visible in cost, in euros per year."),
    "Retorno": c("Valor que no es ahorro: más ingresos o margen, pérdidas o fraude evitados, en euros al año.", "Return", "Value that is not savings: more revenue or margin, losses or fraud avoided, in euros per year."),
    "Retorno total": c("Eficiencias más retorno, en euros al año.", "Total return", "Efficiencies plus return, in euros per year."),
    "Eficiencias + retorno": c("Valor anual del caso: ahorro materializado más retorno.", "Efficiencies + return", "Annual value of the case: materialised savings plus return."),
    "Eficiencias · retorno": c("Valor anual de los casos del grupo: ahorro materializado y retorno.", "Efficiencies · return", "Annual value of the cases in the group: materialised savings and return."),
    "Capacidad no materializada": c("Horas liberadas por la IA que aún no se han convertido en menor coste ni en trabajo reasignado. Se muestra, pero <b>no suma</b> en el neto.", "Unmaterialised capacity", "Hours freed by AI that have not yet become lower cost or reassigned work. Shown, but it <b>does not add</b> to the net."),
    "Capacidad liberada (no suma)": c("Valor de las horas liberadas en la unidad; no suma en el neto hasta que se materializa.", "Freed capacity (does not add)", "Value of the hours freed in the unit; it does not add to the net until it materialises."),
    "Neto anual": c("Eficiencias + retorno − coste anual. Negativo: el caso cuesta más de lo que aporta o no mide su valor.", "Annual net", "Efficiencies + return − annual cost. Negative: the case costs more than it brings or does not measure its value."),
    "= Neto anual": c("Resultado: retorno total menos costes.", "= Annual net", "Result: total return minus costs."),
    "Neto": c("Retorno total menos costes, en euros al año.", "Net", "Total return minus costs, in euros per year."),
    "Neto potencial": c("Neto anual que daría el caso si se cumplen sus hipótesis, con la inversión adicional y en el plazo indicados.", "Potential net", "Annual net the case would deliver if its hypotheses hold, with the stated additional investment and timeframe."),
    "Neto anual actual": c("Lo que el caso aporta hoy, neto de su coste.", "Current annual net", "What the case brings today, net of its cost."),
    "Neto anual potencial": c("Lo que aportaría con su potencial alcanzado.", "Potential annual net", "What it would bring once its potential is reached."),
    "Inversión adicional": c("Inversión que falta para llegar al potencial (ampliar, escalar, integrar).", "Additional investment", "Investment still needed to reach the potential (extend, scale, integrate)."),
    "€ neto por € adicional": c("Euros de neto anual adicional por cada euro de inversión adicional. Más alto, mejor destino para el siguiente euro.", "Net € per additional €", "Euros of additional annual net per euro of additional investment. Higher means a better destination for the next euro."),
    "Plazo del potencial": c("Cuándo se espera alcanzar el potencial.", "Potential timeframe", "When the potential is expected to be reached."),
    "Construcción recuperada en": c("Tiempo para recuperar la construcción con el neto anual actual (construcción ÷ neto anual).", "Build paid back in", "Time to recover the build cost with the current annual net (build ÷ annual net)."),
    "Inversión acumulada estimada": c("Construcción más el coste recurrente de todos los años en uso.", "Estimated cumulative investment", "Build plus the recurring cost of every year in use."),
    "Casos con neto negativo": c("Casos en uso que cuestan más de lo que aportan o que no miden su valor.", "Cases with negative net", "Cases in use that cost more than they bring or do not measure their value."),
    "Concepto": c("Línea de coste o de valor (por ejemplo, licencias, consumo, horas ahorradas, ingresos).", "Item", "Cost or value line (for example licences, consumption, hours saved, revenue)."),
    "Actual (€/año)": c("Importe de hoy y su estado (validado, declarado o estimado).", "Current (€/year)", "Today's amount and its status (validated, declared or estimated)."),
    "Potencial (€/año)": c("Importe con el potencial alcanzado.", "Potential (€/year)", "Amount with the potential reached."),
    "Cómo se calcula": c("Fórmula, atribución a la IA, hipótesis y fuente del importe.", "How it is calculated", "Formula, attribution to AI, hypotheses and source of the amount."),
    "Importe": c("Cantidad en euros.", "Amount", "Amount in euros."),
    "Dato y cálculo": c("Estado del dato y cómo se ha calculado.", "Data and calculation", "Status of the figure and how it was calculated."),
    "Peso": c("Porcentaje que representa sobre el total.", "Share", "Percentage of the total."),
    "Total": c("Suma de las columnas anteriores.", "Total", "Sum of the previous columns."),
    "Tipo": c("Clase del elemento (en movimientos: alta, retirada o reevaluación; en incidentes: deriva, error, caída o seguridad).", "Type", "Kind of item (in movements: new, withdrawal or re-assessment; in incidents: drift, error, outage or security)."),
    "Desglose del coste recurrente actual": c("Reparto del coste anual por partidas.", "Breakdown of current recurring cost", "Split of the annual cost by item."),
    "€/año": c("Euros al año.", "€/year", "Euros per year."),
    # ---- ciclo de vida y tiempos
    "Días en el estado": c("Días que lleva el caso en su etapa actual.", "Days in status", "Days the case has been in its current stage."),
    "Límite (días)": c("Días máximos fijados para esa etapa en el JSON general de configuración (a calibrar por cada compañía).", "Limit (days)", "Maximum days set for that stage in the general configuration JSON (to be calibrated by each company)."),
    "Límite": c("Días máximos permitidos en la etapa.", "Limit", "Maximum days allowed in the stage."),
    "Plazo en el estado": c("Semáforo del tiempo en la etapa: en plazo, cerca del límite (amarillo) o fuera de plazo (rojo).", "Time in status", "Traffic light for time in the stage: on time, close to the limit (amber) or overdue (red)."),
    "Plazo": c("En plazo, cerca del límite (amarillo) o fuera de plazo (rojo).", "Timing", "On time, close to the limit (amber) or overdue (red)."),
    "% del límite": c("Días en la etapa sobre su límite. Desde el 80 % se marca en amarillo; por encima del 100 %, en rojo.", "% of limit", "Days in the stage over its limit. From 80% it turns amber; above 100%, red."),
    "Días": c("Días transcurridos en la etapa o estado.", "Days", "Days elapsed in the stage or status."),
    "Desde": c("Fecha de entrada en el estado.", "From", "Date of entry into the status."),
    "Hasta": c("Fecha de salida del estado (vacía si sigue en él).", "To", "Date of exit from the status (empty if still in it)."),
    "Cifras al entrar en el estado": c("Coste, eficiencias y retorno que tenía el caso al entrar en ese estado («prev.» = previstos).", "Figures on entering the status", "Cost, efficiencies and return the case had when it entered that status («prev.» = expected)."),
    "En la etapa desde": c("Fecha en que el caso entró en la etapa actual.", "In the stage since", "Date the case entered its current stage."),
    "Salió desde": c("Etapa en la que estaba el caso cuando se paró o se retiró.", "Exited from", "Stage the case was in when it was stopped or withdrawn."),
    "Fecha de salida": c("Fecha de la decisión de parar o retirar.", "Exit date", "Date of the decision to stop or withdraw."),
    "Días en el embudo": c("Días desde la primera fecha del caso hasta su salida.", "Days in the funnel", "Days from the case's first date to its exit."),
    "Motivo": c("Por qué se paró o se retiró el caso, y qué se aprendió.", "Reason", "Why the case was stopped or withdrawn, and what was learned."),
    "Desviación …": c("Días en la etapa menos la mediana (o la media) de esa etapa; positivo, más lento que lo habitual.", "Deviation …", "Days in the stage minus the median (or mean) for that stage; positive means slower than usual."),
    "Estancias": c("Número de veces que algún caso ha pasado por ese estado (cerradas y en curso).", "Stays", "Number of times a case has gone through that status (closed and ongoing)."),
    "Media": c("Promedio de días. Una estancia muy larga la sube mucho.", "Mean", "Average days. One very long stay pushes it up a lot."),
    "Mediana": c("Días del caso central: la mitad tarda menos y la mitad más. Resiste mejor los casos extremos que la media.", "Median", "Days of the middle case: half take less and half more. Less distorted by extreme cases than the mean."),
    "P25 – P75": c("Rango donde está la mitad central de los casos (del percentil 25 al 75).", "P25 – P75", "Range holding the middle half of the cases (25th to 75th percentile)."),
    "Mín – máx": c("Estancia más corta y más larga.", "Min – max", "Shortest and longest stay."),
    "Superan el límite": c("Estancias que pasaron del límite de días.", "Over the limit", "Stays that exceeded the day limit."),
    "Ahora en el estado": c("Casos que están hoy en ese estado.", "Now in the status", "Cases in that status today."),
    "Frente a la mediana": c("Diferencia con la mediana del estado.", "Versus the median", "Difference from the status median."),
    "Frente a la mediana total": c("Diferencia de ese grupo con la mediana de todos los casos.", "Versus the overall median", "Difference of that group from the median of all cases."),
    "Grupo": c("Valor de la dimensión elegida (por ejemplo, una tecnología o una compañía).", "Group", "Value of the chosen dimension (for example a technology or a company)."),
    "Con fechas": c("Casos del grupo que tienen fechas de cambio de estado; solo con ellos se miden tiempos.", "With dates", "Cases in the group with status-change dates; times are measured only with them."),
    "Trimestre": c("Trimestre natural.", "Quarter", "Calendar quarter."),
    "Entradas": c("Casos que entraron en el embudo en el trimestre.", "Entries", "Cases that entered the funnel in the quarter."),
    "Ganados (a producción)": c("Casos que llegaron a producción en el trimestre.", "Won (to production)", "Cases that reached production in the quarter."),
    "Perdidos": c("Casos no aprobados, descartados o desenganchados en el trimestre.", "Lost", "Cases not approved, discarded or disengaged in the quarter."),
    "Saldo en curso": c("Entradas menos ganados y perdidos: si crece, el embudo se está llenando.", "Net in progress", "Entries minus won and lost: if it grows, the funnel is filling up."),
    "Casos": c("Número de casos.", "Cases", "Number of cases."),
    "Casos de uso": c("Número de casos del grupo.", "Use cases", "Number of cases in the group."),
    "En uso": c("Casos en producción.", "In use", "Cases in production."),
    # ---- movimientos, histórico
    "Fecha": c("Fecha del hecho.", "Date", "Date of the event."),
    "Decisor": c("Órgano o persona que tomó la decisión.", "Decision-maker", "Body or person that took the decision."),
    "Sustituto": c("Caso o solución que sustituye al retirado.", "Replacement", "Case or solution replacing the withdrawn one."),
    "Foto": c("Fecha y nombre de la foto guardada al cierre de una sesión del consejo.", "Snapshot", "Date and name of the snapshot saved at the close of a board session."),
    "Movimiento": c("Qué ha cambiado: nuevo, puesto en producción, retirado, cambio de estado o de neto.", "Change", "What changed: new, put into production, withdrawn, status or net change."),
    "Detalle": c("Estado anterior y actual, o importes antes y después.", "Detail", "Previous and current status, or amounts before and after."),
    # ---- agilidad
    "Riesgo …": c("Tiempos de los casos con ese nivel de riesgo: mediana de días de la idea a la aprobación y de la aprobación a producción, y el plazo comprometido (SLA).", "Risk …", "Times for cases with that risk level: median days from idea to approval and from approval to production, and the committed timeframe (SLA)."),
    "Vía rápida": c("Porcentaje de iniciativas que siguieron la vía rápida de aprobación (bajo riesgo).", "Fast track", "Share of initiatives that followed the fast approval track (low risk)."),
    "Aprobación a la primera": c("Porcentaje de casos aprobados sin tener que volver a presentarse.", "First-time approval", "Share of cases approved without being resubmitted."),
    "Ciclo del comité": c("Días medios que tarda el comité en decidir.", "Committee cycle", "Average days the committee takes to decide."),
    "Backlog sin análisis": c("Casos pendientes de análisis de riesgo y cuánto llevan esperando.", "Backlog without analysis", "Cases awaiting risk analysis and how long they have been waiting."),
    # ---- riesgo regulatorio e incidentes
    "Nivel": c("Nivel de riesgo según el Reglamento de IA.", "Level", "Risk level under the AI Act."),
    "Estimación …": c("Clasificación que estima el consejo asesor, sin criterio jurídico de la compañía.", "Estimate …", "Classification estimated by the advisory board, without the company's legal assessment."),
    "Origen": c("Quién causó el incidente: agente atacante externo, agente propio manipulado, proveedor, error interno.", "Origin", "What caused the incident: external attacking agent, own agent manipulated, supplier, internal error."),
    "Descripción": c("Qué pasó y, si se conoce, por dónde entró el ataque (vector).", "Description", "What happened and, if known, how the attack got in (vector)."),
    "Detectar / contener / resolver": c("Horas hasta detectarlo, contenerlo y resolverlo; entre paréntesis, el objetivo de recuperación (RTO).", "Detect / contain / resolve", "Hours to detect, contain and resolve it; in brackets, the recovery time objective (RTO)."),
    "Brecha de datos": c("Si afectó a datos personales (brecha del RGPD).", "Data breach", "Whether personal data were affected (GDPR breach)."),
    "AEPD (72 h)": c("Si se notificó a la autoridad de protección de datos dentro de las 72 horas que exige el RGPD.", "DPA (72 h)", "Whether the data protection authority was notified within the 72 hours required by the GDPR."),
    "DORA": c("Si se notificó como incidente según DORA (resiliencia operativa digital del sector financiero).", "DORA", "Whether it was notified as an incident under DORA (digital operational resilience in the financial sector)."),
    "Contención": c("Porcentaje de consultas que el asistente resuelve sin pasar a una persona.", "Containment", "Share of queries the assistant resolves without handing over to a person."),
    "Derivación": c("Porcentaje de consultas que pasan a una persona.", "Hand-over", "Share of queries handed over to a person."),
    "Guardarraíl": c("Porcentaje de respuestas en las que saltó un guardarraíl (filtro de seguridad o de contenido).", "Guardrail", "Share of answers in which a guardrail (safety or content filter) fired."),
    "QA humano": c("Porcentaje de respuestas revisadas por una persona para medir su calidad.", "Human QA", "Share of answers reviewed by a person to measure quality."),
    "Evals": c("Fecha de la última evaluación con un conjunto de pruebas del comportamiento.", "Evals", "Date of the last evaluation against a behaviour test set."),
    "Red teaming": c("Fecha de la última prueba adversaria (intentos deliberados de hacerle fallar).", "Red teaming", "Date of the last adversarial test (deliberate attempts to make it fail)."),
    # ---- agentes
    "Acciones": c("Qué puede hacer el agente: leer, escribir en sistemas o ejecutar pagos.", "Actions", "What the agent can do: read, write to systems or execute payments."),
    "Identidades · credenciales": c("Cuántas identidades técnicas usa y de qué tipo son sus credenciales.", "Identities · credentials", "How many technical identities it uses and the type of its credentials."),
    "Mínimo privilegio": c("Si solo tiene los permisos imprescindibles para su tarea.", "Least privilege", "Whether it only has the permissions strictly needed for its task."),
    "Rotación": c("Cada cuántos días se cambian sus claves y tokens.", "Rotation", "Every how many days its keys and tokens are changed."),
    "Control de intención": c("Si un control externo al modelo autoriza cada acción antes de ejecutarla (IBAC).", "Intent control", "Whether a control outside the model authorises each action before it runs (IBAC)."),
    "Validación humana": c("Si una persona valida las acciones que escriben o pagan.", "Human validation", "Whether a person validates the actions that write or pay."),
    "Parada": c("Si existe un botón de parada que detiene al agente de inmediato.", "Stop", "Whether a kill switch exists that stops the agent immediately."),
    "Registro de acciones": c("Porcentaje de acciones del agente que quedan registradas para reconstruir qué hizo.", "Action logging", "Share of the agent's actions logged so what it did can be reconstructed."),
    "Prueba de inyección": c("Fecha de la última prueba de inyección de instrucciones (prompt injection).", "Injection test", "Date of the last prompt-injection test."),
    "Proveedor DORA": c("Si su proveedor está en el registro de proveedores de TIC y con qué criticidad.", "DORA supplier", "Whether its supplier is in the ICT supplier register and with which criticality."),
    # ---- índice de transformación
    "Señal": c("Cada una de las ocho señales del índice: 1 composición de la inversión, 2 composición del valor, 3 materialización, 4 profundidad del cambio, 5 modelo operativo, 6 ingresos habilitados por IA, 7 paso a producción y 8 decisión del consejo.", "Signal", "Each of the index's eight signals: 1 investment mix, 2 value mix, 3 materialisation, 4 depth of change, 5 operating model, 6 AI-enabled revenue, 7 move to production and 8 board decision."),
    "Valor medido": c("La cifra con la que se puntúa la señal (un porcentaje, un cociente o un recuento).", "Measured value", "The figure used to score the signal (a percentage, a ratio or a count)."),
    "Puntuación (0–3)": c("0 exploración o sin medir, 1 eficiencia, 2 intermedia, 3 transformación, según los umbrales del documento 12.", "Score (0–3)", "0 exploration or not measured, 1 efficiency, 2 intermediate, 3 transformation, according to the thresholds of document 12."),
    "Lectura": c("La puntuación dicha en palabras.", "Reading", "The score in words."),
    "Tendencia": c("Cambio frente al cálculo o diagnóstico anterior: ▲ sube, ▼ baja, = igual, — sin cálculo anterior.", "Trend", "Change against the previous calculation or assessment: ▲ up, ▼ down, = same, — no previous calculation."),
    # ---- madurez
    "Dimensión": c("Cada una de las siete dimensiones de madurez del documento 11: D1 Estrategia y gobierno, D2 Valor y cartera, D3 Datos y conocimiento, D4 Tecnología y operación, D5 Personas y adopción, D6 Riesgo, seguridad y cumplimiento y D7 Medición y evidencia.", "Dimension", "Each of the seven maturity dimensions of document 11: D1 Strategy and governance, D2 Value and portfolio, D3 Data and knowledge, D4 Technology and operations, D5 People and adoption, D6 Risk, security and compliance and D7 Measurement and evidence."),
    "Nivel (0–5)": c("0 Inexistente, 1 Inicial, 2 En desarrollo, 3 Definido, 4 Gestionado, 5 Optimizado. Un nivel se alcanza cuando se cumplen todos sus criterios.", "Level (0–5)", "0 Non-existent, 1 Initial, 2 Developing, 3 Defined, 4 Managed, 5 Optimised. A level is reached when all its criteria are met."),
    "Avance al nivel siguiente": c("Porcentaje de los criterios del nivel siguiente que ya se cumplen.", "Progress to next level", "Share of the next level's criteria already met."),
    "Bloqueantes": c("Códigos de los criterios que faltan e impiden subir de nivel: es la lista de trabajo.", "Blockers", "Codes of the missing criteria that prevent moving up a level: it is the to-do list."),
    # ---- transversales
    "Despliegue": c("Situación en la unidad: previsto, piloto, en uso o retirado, con su fecha.", "Roll-out", "Status in the unit: planned, pilot, in use or withdrawn, with its date."),
    "Licencias activas / asignadas": c("Licencias usadas de verdad sobre las pagadas; en rojo si está por debajo del umbral de adopción.", "Active / assigned licences", "Licences actually used over those paid for; red if below the adoption threshold."),
    "Horas liberadas al mes (declaradas)": c("Horas que la unidad dice ahorrar cada mes; es una declaración, no un ahorro validado.", "Hours freed per month (declared)", "Hours the unit says it saves each month; a declaration, not a validated saving."),
    "Valor materializado": c("Lo que ya se ha convertido en menor coste o en capacidad reasignada con destino; lo único que llega al neto. Debajo, cuánto está validado.", "Materialised value", "What has already turned into lower cost or capacity reassigned to a purpose; the only part that reaches the net. Below, how much is validated."),
    # ---- cuadro de mando de la compañía
    "VNB acumulado (compañía)": c("Valor de nuevo negocio acumulado que declara el cuadro de mando de la compañía.", "Cumulative NBV (company)", "Cumulative new business value declared by the company's scorecard."),
    "Extrapolación anterior del …": c("Lo que el consejo asesor había extrapolado antes de tener el dato de la compañía.", "Previous extrapolation by …", "What the advisory board had extrapolated before having the company's figure."),
    "PTA acumulada": c("Primas acumuladas; mide las mismas ventas que el VNB, por eso no se suma.", "Cumulative premiums", "Cumulative premiums; they measure the same sales as NBV, so they are not added."),
    "VNB / PTA": c("Cociente entre valor de nuevo negocio y primas.", "NBV / premiums", "Ratio of new business value to premiums."),
    "Magnitud": c("Cifra que se compara entre dos páginas del mismo documento.", "Measure", "Figure compared between two pages of the same document."),
    "p. 50": c("Valor en los titulares de la página 50 del cuadro de mando.", "p. 50", "Value in the headlines on page 50 of the scorecard."),
    "p. 51-52": c("Valor en el detalle de las páginas 51 y 52.", "pp. 51-52", "Value in the detail on pages 51 and 52."),
    "Diferencia": c("Titular menos detalle: si no es cero, el documento no cuadra.", "Difference", "Headline minus detail: if not zero, the document does not add up."),
    "Coste declarado por la compañía": c("Coste acumulado que da la compañía para esos casos.", "Cost declared by the company", "Cumulative cost the company gives for those cases."),
    "Estimación ilustrativa del …": c("Coste acumulado que estima el consejo asesor; se mantiene porque el dato declarado parece incompleto.", "Illustrative estimate by …", "Cumulative cost estimated by the advisory board; kept because the declared figure looks incomplete."),
    "VNB neto según la compañía": c("VNB acumulado menos coste declarado.", "Net NBV according to the company", "Cumulative NBV minus declared cost."),
    "Eficiencia en costes y en tiempos": c("Eficiencias que declara el cuadro de mando (vacías si no las informa).", "Cost and time efficiency", "Efficiencies declared by the scorecard (empty if not reported)."),
    # ---- exposición a ataques con IA
    "Doble factor en aplicaciones expuestas": c("Porcentaje de aplicaciones accesibles desde internet que exigen doble factor de autenticación.", "MFA on exposed applications", "Share of internet-facing applications that require multi-factor authentication."),
    "Vulnerabilidades críticas abiertas > 30 días": c("Vulnerabilidades críticas sin corregir más de 30 días y días medios de cierre.", "Critical vulnerabilities open > 30 days", "Critical vulnerabilities unpatched for more than 30 days and average days to close."),
    "Horas hasta detectar / contener": c("Mediana de horas hasta detectar un incidente y hasta contenerlo.", "Hours to detect / contain", "Median hours to detect an incident and to contain it."),
    "Identidades de agentes con permisos excesivos": c("Identidades de agentes con más permisos de los necesarios, sobre el total.", "Agent identities with excessive permissions", "Agent identities with more permissions than needed, out of the total."),
    "Agentes que escriben o pagan sin validación humana": c("Agentes que modifican sistemas o pagan sin que una persona lo valide.", "Agents that write or pay without human validation", "Agents that change systems or pay without a person validating it."),
    "Brechas de datos / notificadas en 72 h": c("Brechas de datos personales del periodo y cuántas se notificaron a tiempo.", "Data breaches / notified within 72 h", "Personal data breaches in the period and how many were notified on time."),
    "Prueba de intrusión con IA ofensiva": c("Fecha de la última prueba de intrusión con un atacante asistido por IA.", "Penetration test with offensive AI", "Date of the last penetration test with an AI-assisted attacker."),
    "Éxito de la inyección de instrucciones": c("Porcentaje de ataques de inyección de instrucciones que superan los guardarraíles en pruebas. Más bajo, mejor.", "Prompt-injection success rate", "Share of prompt-injection attacks that get past the guardrails in tests. Lower is better."),
    "Tratamientos con riesgo de IA ofensiva analizado": c("Tratamientos de datos personales cuyo análisis de riesgo contempla ataques con IA, sobre el total.", "Processing activities with offensive-AI risk analysed", "Personal data processing activities whose risk analysis covers AI attacks, out of the total."),
    "Acciones de agentes registradas": c("Porcentaje de acciones de agentes que quedan registradas.", "Agent actions logged", "Share of agent actions that are logged."),
    "Detección de tráfico automatizado": c("Si se detectan bots y agentes que operan a velocidad de máquina.", "Automated traffic detection", "Whether bots and agents operating at machine speed are detected."),
    "Runbook de incidentes de IA": c("Si hay un procedimiento aprobado de respuesta a incidentes de IA.", "AI incident runbook", "Whether there is an approved AI incident response procedure."),
    "Simulacro con agente atacante": c("Fecha del último ejercicio de crisis con un agente atacante.", "Drill with an attacking agent", "Date of the last crisis exercise with an attacking agent."),
    "Ensayo de notificación en 72 h": c("Fecha del último ensayo de notificación a la autoridad en 72 horas (RGPD y DORA).", "72-hour notification rehearsal", "Date of the last rehearsal of notifying the authority within 72 hours (GDPR and DORA)."),
    # ---- adopción
    "Copilot · licencias activas": c("Licencias de Copilot usadas sobre asignadas y usuarios activos por semana.", "Copilot · active licences", "Copilot licences used over assigned and weekly active users."),
    "Claude · licencias activas": c("Licencias de Claude usadas sobre asignadas y usuarios activos por semana.", "Claude · active licences", "Claude licences used over assigned and weekly active users."),
    "Plataforma agéntica": c("Conversaciones al mes y usuarios activos de la plataforma de agentes.", "Agentic platform", "Conversations per month and active users of the agent platform."),
    "Shadow AI detectada": c("Herramientas o usos de IA fuera de los canales aprobados que se han detectado.", "Shadow AI detected", "AI tools or uses outside approved channels that have been detected."),
    "Controles técnicos frente al shadow AI": c("Cuántos de tres controles están activos: prevención de fuga de datos (DLP), filtrado de navegación y gestión de dispositivos.", "Technical controls against shadow AI", "How many of three controls are active: data loss prevention (DLP), web filtering and device management."),
    "Formación": c("Porcentaje del personal obligado que ha completado la formación en IA.", "Training", "Share of the staff required to be trained who have completed AI training."),
    "Vacantes clave": c("Puestos críticos para la IA sin cubrir.", "Key vacancies", "Critical AI positions unfilled."),
    "Rotación del equipo": c("Porcentaje del equipo de IA que se ha ido en los últimos doce meses.", "Team turnover", "Share of the AI team that left in the last twelve months."),
    # ---- desglose de indicadores (fichas de KPI)
    "Control": c("Control obligatorio que falta.", "Control", "Mandatory control that is missing."),
    "Qué hacer": c("Acción para completarlo.", "What to do", "Action to complete it."),
}


def t(titulo, que, porque, donde="", leer=""):
    d = {"titulo": titulo, "que": que, "porque": porque}
    if donde: d["donde"] = donde
    if leer: d["leer"] = leer
    return d


TARJETAS = {
    # ---- Cartera y valor: indicadores de cabecera
    "kpi-casos": {
        "es": t("Casos seleccionados",
                "Cuántos casos de uso cumplen los filtros y la búsqueda, repartidos por estado; cuántos no tienen descripción y, si se compara con una foto guardada, cuántos son nuevos o han pasado a producción desde entonces.",
                "Es la base de todas las cifras de la página: antes de leer un importe hay que saber sobre qué casos se calcula. Un caso sin descripción no se puede defender ante el consejo.",
                "documento 14 (gestión de cartera)",
                "El número grande es el total de casos; debajo, cuántos hay en cada estado del embudo."),
        "en": t("Selected cases",
                "How many use cases match the filters and the search, split by status; how many have no description and, when compared with a saved snapshot, how many are new or have gone into production since then.",
                "It is the basis of every figure on the page: before reading an amount you need to know which cases it is calculated on. A case without a description cannot be defended before the board.",
                "document 14 (portfolio management)",
                "The large number is the total of cases; below, how many are in each funnel status."),
    },
    "kpi-costes": {
        "es": t("Costes",
                "Coste recurrente anual de los casos seleccionados (en régimen, si se mira el potencial), inversión de construcción, inversión adicional para llegar al potencial y cuántos casos tienen el coste estimado en lugar de declarado. Al pulsar la tarjeta se abre el desglose.",
                "El valor solo se entiende frente a su coste completo (licencias, consumo, personas, integración y mantenimiento). Los costes estimados señalan dónde falta el dato de la compañía.",
                "documento 42 (costes de IA)",
                "El número grande es el coste de cada año; la construcción se paga una sola vez y no está incluida en él. La flecha compara con la foto elegida: en costes, subir es peor."),
        "en": t("Costs",
                "Annual recurring cost of the selected cases (at steady state when looking at the potential), build investment, additional investment to reach the potential and how many cases have an estimated rather than declared cost. Clicking the card opens the breakdown.",
                "Value only makes sense against its full cost (licences, consumption, people, integration and maintenance). Estimated costs show where the company's figure is missing.",
                "document 42 (AI costs)",
                "The large number is the yearly cost; the build is paid once and is not included in it. The arrow compares with the chosen snapshot: for costs, going up is worse."),
        "columnas": ["Coste anual", "Inversión de construcción", "Inversión adicional", "Coste estimado"],
    },
    "kpi-retorno": {
        "es": t("Retorno total",
                "Eficiencias materializadas más retorno (ingresos, margen o pérdidas evitadas) de los casos seleccionados. La capacidad liberada que no se ha materializado se muestra aparte y no suma. Al pulsar la tarjeta se abre el desglose.",
                "Separa el valor que ya llega a la cuenta de resultados de las horas liberadas que todavía no se han convertido en menor coste ni en capacidad reasignada: sumarlas inflaría el valor de la IA.",
                "documento 40 (reglas de medición del valor)",
                "Euros al año. «Actual» es lo que ya se produce; «Potencial», lo máximo alcanzable con las hipótesis de cada caso."),
        "en": t("Total return",
                "Materialised efficiencies plus return (revenue, margin or losses avoided) of the selected cases. Freed capacity that has not materialised is shown separately and does not add up. Clicking the card opens the breakdown.",
                "It separates the value that already reaches the P&amp;L from freed hours that have not yet become lower cost or reassigned capacity: adding them would inflate the value of AI.",
                "document 40 (value measurement rules)",
                "Euros per year. «Current» is what is produced today; «Potential» is the maximum reachable with each case's hypotheses."),
        "columnas": ["Eficiencias materializadas", "Retorno", "Capacidad no materializada"],
    },
    "kpi-neto": {
        "es": t("Neto anual",
                "Retorno total menos costes recurrentes de los casos seleccionados; en potencial, cuánto más daría la cartera y con qué inversión adicional; y cuántos casos en uso tienen neto negativo.",
                "Responde a la pregunta del consejo: ¿la cartera de IA aporta o consume dinero cada año? Un caso en uso con neto negativo es candidato a iterar o retirar en G7.",
                "documento 40 y documento 43 (realización de beneficios)",
                "Positivo: la cartera aporta más de lo que cuesta cada año. No incluye la construcción, que se recupera con el neto (ver la ficha de cada caso)."),
        "en": t("Annual net",
                "Total return minus recurring costs of the selected cases; in potential, how much more the portfolio would deliver and with what additional investment; and how many cases in use have a negative net.",
                "It answers the board's question: does the AI portfolio earn or consume money each year? A case in use with a negative net is a candidate to iterate or withdraw at G7.",
                "document 40 and document 43 (benefits realisation)",
                "Positive: the portfolio brings more than it costs each year. It does not include the build, which is recovered through the net (see each case's record)."),
        "columnas": ["Retorno total", "− Costes", "= Neto anual", "Casos con neto negativo"],
    },
    "kpi-validado": {
        "es": t("Valor actual validado",
                "Qué parte del valor actual está validada por una función independiente (Control de Gestión), frente a la declarada por la compañía y la estimada por el consejo asesor.",
                "Un valor declarado por quien construye el caso no es una evidencia. Antes de decidir inversiones sobre una cifra, el consejo debe saber cuánto de ella ha comprobado alguien que no la defiende.",
                "documento 40",
                "Porcentaje del valor actual que está validado. Color: verde en objetivo, amarillo por debajo del primer umbral, rojo por debajo del segundo; los umbrales se ven en la propia tarjeta y se fijan en el JSON general de configuración."),
        "en": t("Current value validated",
                "Which share of current value has been validated by an independent function (Management Control), compared with the value declared by the company and estimated by the advisory board.",
                "A value declared by whoever builds the case is not evidence. Before deciding investments on a figure, the board must know how much of it was checked by someone who does not defend it.",
                "document 40",
                "Share of current value that is validated. Colour: green on target, amber below the first threshold, red below the second; the thresholds are shown on the card and set in the general configuration JSON."),
    },
    "kpi-clasificados": {
        "es": t("Clasificados por la compañía",
                "Casos con clasificación según el Reglamento de IA hecha por la compañía con criterio jurídico, frente al total; el resto solo tiene la estimación del consejo asesor.",
                "La clasificación decide las obligaciones (prácticas prohibidas, alto riesgo, transparencia) y las sanciones. Un caso sin clasificar es un riesgo de cumplimiento sin medir.",
                "documento 32 (inventario y clasificación) y documento 34 (mapeo regulatorio)",
                "«13 de 15»: casos clasificados sobre el total. El color sigue los umbrales que se ven en la tarjeta."),
        "en": t("Classified by the company",
                "Cases classified under the AI Act by the company with legal criteria, out of the total; the rest only have the advisory board's estimate.",
                "The classification determines obligations (prohibited practices, high risk, transparency) and sanctions. An unclassified case is an unmeasured compliance risk.",
                "document 32 (inventory and classification) and document 34 (regulatory mapping)",
                "«13 of 15»: classified cases out of the total. The colour follows the thresholds shown on the card."),
    },
    "kpi-controles": {
        "es": t("Casos con controles completos",
                "Casos con todos sus controles hechos o marcados como no aplicables: clasificación regulatoria, evaluación de impacto en derechos fundamentales (FRIA), evaluación de impacto en protección de datos (DPIA), seguridad, manual de uso y control (MUC) y análisis del riesgo de ataques con IA.",
                "Un caso en producción sin sus controles expone a la compañía a sanciones, incidentes y daño reputacional. El color muestra de un vistazo si la cobertura está en objetivo.",
                "documento 33 (riesgos) y documento 35 (seguridad)",
                "Casos completos sobre el total. El detalle por control está en «Riesgo y cumplimiento», tarjeta «Semáforo regulatorio»."),
        "en": t("Cases with complete controls",
                "Cases with all their controls done or marked as not applicable: regulatory classification, fundamental rights impact assessment (FRIA), data protection impact assessment (DPIA), security, user and control manual and AI-attack risk analysis.",
                "A case in production without its controls exposes the company to sanctions, incidents and reputational damage. The colour shows at a glance whether coverage is on target.",
                "document 33 (risks) and document 35 (security)",
                "Complete cases out of the total. The detail by control is under «Risk and compliance», card «Regulatory traffic light»."),
    },
    # ---- Cartera y valor: tarjetas
    "c1": {
        "es": t("Eficiencias, retorno y coste por compañía y unidad",
                "Para cada compañía y unidad de negocio, una barra con las eficiencias, el retorno y la capacidad no materializada, y debajo otra con el coste recurrente; actual o potencial según el selector de la barra superior.",
                "Muestra dónde se concentran el valor y el coste de la IA. Una unidad con mucho coste y poco retorno, o con valor solo en capacidad no materializada, pide una conversación con su responsable de negocio.",
                "documento 40",
                "Cada fila es una unidad. Colores: verde azulado eficiencias, azul retorno, azul claro capacidad no materializada (no suma), ocre coste anual. Si la barra de valor es más corta que la de coste, la unidad pierde dinero. Pase el ratón por una barra para ver sus cifras."),
        "en": t("Efficiencies, return and cost by company and unit",
                "For each company and business unit, a bar with efficiencies, return and unmaterialised capacity, and below it a bar with the recurring cost; current or potential depending on the selector in the top bar.",
                "It shows where the value and cost of AI are concentrated. A unit with high cost and little return, or with value only in unmaterialised capacity, calls for a conversation with its business owner.",
                "document 40",
                "Each row is a unit. Colours: teal efficiencies, blue return, light blue unmaterialised capacity (does not add), ochre annual cost. If the value bar is shorter than the cost bar, the unit is losing money. Hover over a bar to see its figures."),
        "columnas": ["Eficiencias", "Retorno", "Capacidad no materializada", "Coste anual"],
    },
    "c2": {
        "es": t("Dónde rinde más la inversión adicional",
                "Los casos (hasta quince) con inversión adicional estimada y neto adicional positivo, ordenados por euros de neto anual adicional por cada euro invertido. Al pulsar una barra se abre la economía del caso.",
                "Ayuda a decidir dónde poner el siguiente euro: escalar lo que ya funciona suele rendir más que abrir casos nuevos. Son cifras potenciales: dependen de las hipótesis y del plazo de cada caso.",
                "documento 14 y documento 40",
                "Barra oscura: neto anual adicional que se ganaría; barra ocre: inversión adicional necesaria. Arriba, los que más devuelven por euro."),
        "en": t("Where additional investment pays off most",
                "Cases (up to fifteen) with an estimated additional investment and a positive additional net, ranked by euros of additional annual net per euro invested. Clicking a bar opens the case's economics.",
                "It helps decide where to put the next euro: scaling what already works usually pays off more than opening new cases. These are potential figures: they depend on each case's hypotheses and timeframe.",
                "document 14 and document 40",
                "Dark bar: additional annual net that would be gained; ochre bar: additional investment needed. At the top, those returning most per euro."),
        "columnas": [propia("Neto anual adicional", "Neto anual que se sumaría al alcanzar el potencial.", "Additional annual net", "Annual net that would be added when the potential is reached."), "Inversión adicional", "€ neto por € adicional"],
    },
    "cdm": {
        "es": t("Cuadro de mando de la compañía frente a este panel",
                "Compara, caso a caso, el valor que declara el cuadro de mando de la compañía con el de este panel, y recoge las incoherencias del propio documento y las advertencias sobre él.",
                "El consejo recibe a menudo dos cifras de valor distintas. Esta tarjeta explica de dónde sale la diferencia y qué dato falta, para que la decisión no dependa de la fuente que se mire.",
                "documento 60 (paquete para el consejo)"),
        "en": t("Company scorecard versus this dashboard",
                "It compares, case by case, the value declared in the company's scorecard with this dashboard's, and lists the inconsistencies of the document itself and the warnings about it.",
                "The board often receives two different value figures. This card explains where the difference comes from and which figure is missing, so the decision does not depend on which source is looked at.",
                "document 60 (board pack)"),
        "columnas": ["Caso", "VNB acumulado (compañía)", "Extrapolación anterior del …",
                     propia("Desviación", "Diferencia entre la extrapolación anterior y el dato de la compañía, en porcentaje.", "Deviation", "Difference between the previous extrapolation and the company's figure, as a percentage."),
                     "PTA acumulada", "VNB / PTA", "Magnitud", "p. 50", "p. 51-52", "Diferencia",
                     "Coste declarado por la compañía", "Estimación ilustrativa del …", "VNB neto según la compañía", "Eficiencia en costes y en tiempos"],
    },
    "indice": {
        "es": t("Índice de transformación",
                "El último cálculo de la calculadora T14: perfil asignado, condiciones de base (B1 cartera gobernada, B2 valor validado, B3 escala en producción), ocho señales puntuadas de 0 a 3, tendencia frente al cálculo anterior, alertas y qué movería el perfil. Es de la compañía en su conjunto: los filtros no lo cambian.",
                "Responde si la compañía se está transformando con la IA o solo se está haciendo más eficiente, con evidencias y no con declaraciones: una transformación declarada que las señales no respaldan se señala.",
                "documento 12 (índice de transformación)",
                "Perfiles, de menos a más: exploración dispersa, eficiencia táctica, eficiencia a escala y transformación en curso; «transformación declarada, no evidenciada» es una alerta. El perfil no sale de sumar puntos: lo deciden las condiciones de base y las señales clave. La suma (de 0 a 24) y la cobertura (señales medidas de 8) dan contexto. Cada círculo lleno es un punto."),
        "en": t("Transformation index",
                "The latest calculation of the T14 calculator: assigned profile, base conditions (B1 governed portfolio, B2 validated value, B3 scale in production), eight signals scored 0 to 3, trend against the previous calculation, alerts and what would move the profile. It covers the company as a whole: filters do not change it.",
                "It shows whether the company is transforming with AI or only becoming more efficient, with evidence rather than statements: a declared transformation that the signals do not support is flagged.",
                "document 12 (transformation index)",
                "Profiles, from least to most: scattered exploration, tactical efficiency, efficiency at scale and transformation under way; «transformation declared, not evidenced» is an alert. The profile does not come from adding points: base conditions and key signals decide it. The sum (0 to 24) and coverage (signals measured out of 8) give context. Each filled circle is one point."),
        "columnas": ["Señal", "Valor medido", "Puntuación (0–3)", "Lectura", "Tendencia"],
    },
    "madurez": {
        "es": t("Madurez de la compañía (D1–D7)",
                "El último diagnóstico de T15: nivel global y de cada una de las siete dimensiones (0 a 5), avance hacia el nivel siguiente, criterios bloqueantes, límite por estrategia y gobierno (D1) o por riesgo, seguridad y cumplimiento (D6), tendencia y si es un autodiagnóstico o está verificado. Los filtros no lo cambian.",
                "Indica si la compañía tiene capacidad para sostener la cartera y la ambición que se le presentan: subir la ambición sin gobierno ni control del riesgo multiplica el riesgo. Una autoevaluación sin verificar no vale para el consejo.",
                "documento 11 (modelo de madurez)",
                "Niveles: 0 Inexistente, 1 Inicial, 2 En desarrollo, 3 Definido, 4 Gestionado, 5 Optimizado. El nivel global es la media ponderada redondeada hacia abajo y nunca puede superar en más de uno al nivel de D1 (gobierno) o D6 (riesgo): sin control no se presenta más madurez. Los círculos llenos son el nivel; la barra, el avance hacia el siguiente."),
        "en": t("Company maturity (D1–D7)",
                "The latest T15 assessment: overall level and level of each of the seven dimensions (0 to 5), progress towards the next level, blocking criteria, cap by strategy and governance (D1) or by risk, security and compliance (D6), trend and whether it is a self-assessment or verified. Filters do not change it.",
                "It shows whether the company can sustain the portfolio and ambition put before it: raising ambition without governance or risk control multiplies risk. An unverified self-assessment is not valid for the board.",
                "document 11 (maturity model)",
                "Levels: 0 Non-existent, 1 Initial, 2 Developing, 3 Defined, 4 Managed, 5 Optimised. The overall level is the weighted average rounded down and can never be more than one above the level of D1 (governance) or D6 (risk): without control, no higher maturity is presented. Filled circles are the level; the bar, progress towards the next one."),
        "columnas": ["Dimensión", "Nivel (0–5)", "Avance al nivel siguiente", "Bloqueantes", "Tendencia"],
    },
    "transv": {
        "es": t("Iniciativas transversales y plataformas habilitadoras",
                "Las herramientas que usan varias unidades y las plataformas en las que se apoyan otros casos: por unidad, despliegue, adopción (licencias activas sobre asignadas) frente al umbral, horas y capacidad liberadas (no suman), coste y valor materializado; y el neto de la cartera con ellas y sin ellas.",
                "Un asistente en la suite ofimática tiene un coste seguro y un valor difícil de probar. Medirlo por unidad y presentar el neto con y sin estas iniciativas evita que diluyan u oculten el resultado del resto de la cartera.",
                "documento 40 §7.2",
                "Se lee de izquierda a derecha como una escalera: primero el coste, luego si se usa, luego las horas que dice ahorrar y al final lo que de verdad llega al neto. Una plataforma no tiene valor propio: su valor está en los casos que la usan."),
        "en": t("Cross-cutting initiatives and enabling platforms",
                "Tools used by several units and platforms other cases rely on: by unit, roll-out, adoption (active over assigned licences) against the threshold, freed hours and capacity (they do not add), cost and materialised value; and the portfolio net with and without them.",
                "An assistant in the office suite has a certain cost and a value that is hard to prove. Measuring it by unit and presenting the net with and without these initiatives stops them from diluting or hiding the result of the rest of the portfolio.",
                "document 40 §7.2",
                "Read left to right as a ladder: first the cost, then whether it is used, then the hours it claims to save and finally what actually reaches the net. A platform has no value of its own: its value lies in the cases that use it."),
        "columnas": ["Unidad de negocio", "Despliegue", "Licencias activas / asignadas", "Horas liberadas al mes (declaradas)", "Coste anual", "Capacidad liberada (no suma)", "Valor materializado"],
    },
    "cart1": {
        "es": t("Movimientos del periodo",
                "Altas, retiradas y reevaluaciones desde la sesión anterior, con su fecha, motivo, quién lo decidió y qué caso lo sustituye.",
                "Una cartera sana también retira casos. Si nunca hay retiradas, probablemente no se está ejerciendo la capacidad de parar, y el coste de los casos que no aportan sigue corriendo.",
                "documento 14"),
        "en": t("Movements in the period",
                "New cases, withdrawals and re-assessments since the previous session, with their date, reason, who decided and which case replaces them.",
                "A healthy portfolio also withdraws cases. If there are never any withdrawals, the ability to stop is probably not being used, and the cost of cases that bring nothing keeps running.",
                "document 14"),
        "columnas": ["Fecha", propia("Tipo", "Alta (caso nuevo), retirada (se deja de usar) o reevaluación (se revisa su caso de negocio).", "Type", "New (new case), withdrawal (no longer used) or re-assessment (its business case is reviewed)."), "Caso", "Motivo", "Decisor", "Sustituto"],
    },
    "cart2": {
        "es": t("Agilidad por nivel de riesgo",
                "Mediana de días de la idea a la aprobación y de la aprobación a producción, por nivel de riesgo, frente al plazo comprometido (SLA); y el uso de la vía rápida, la aprobación a la primera, el ciclo del comité y los casos pendientes de análisis.",
                "El gobierno no debe convertirse en un freno. Separar por nivel de riesgo muestra si los casos sencillos avanzan rápido y si el tiempo se pierde al arrancar los casos o al entregarlos.",
                "documento 20 (manuales de fase) y documento 21 (criterios de gate)",
                "Un recuadro por nivel de riesgo (bajo, medio, alto). Debajo de cada cifra se indica si sale de las fechas de los casos o de lo que declara la compañía. Lo razonable es que el riesgo bajo sea claramente más rápido que el alto."),
        "en": t("Agility by risk level",
                "Median days from idea to approval and from approval to production, by risk level, against the committed timeframe (SLA); and use of the fast track, first-time approval, the committee cycle and cases awaiting analysis.",
                "Governance must not become a brake. Splitting by risk level shows whether simple cases move fast and whether time is lost when starting cases or when delivering them.",
                "document 20 (phase manuals) and document 21 (gate criteria)",
                "One box per risk level (low, medium, high). Below each figure it says whether it comes from the cases' dates or from what the company declares. Low risk should be clearly faster than high risk."),
        "columnas": ["Riesgo …", "Vía rápida", "Aprobación a la primera", "Ciclo del comité", "Backlog sin análisis"],
    },
    # ---- Embudo y ciclo de vida
    "emb-entradas": {
        "es": t("Entradas en el embudo",
                "Todos los casos seleccionados que han entrado alguna vez en el embudo y, de ellos, cuántos entraron en los últimos doce meses.",
                "Mide si la compañía sigue generando ideas y oportunidades. Sin entradas nuevas, la cartera envejece aunque sus cifras actuales sean buenas.",
                "documento 14"),
        "en": t("Funnel entries",
                "All selected cases that have ever entered the funnel and, of them, how many entered in the last twelve months.",
                "It measures whether the company keeps generating ideas and opportunities. Without new entries the portfolio ages even if its current figures are good.",
                "document 14"),
    },
    "emb-encurso": {
        "es": t("En curso",
                "Casos que están ahora dentro del embudo, repartidos por etapa (propuestos, en hipótesis de valor, en prueba de concepto y en desarrollo).",
                "Es la actividad corriente de la cartera: dice cuánto trabajo hay abierto y en qué etapa se acumula.",
                "documento 20"),
        "en": t("In progress",
                "Cases currently inside the funnel, split by stage (proposed, value hypothesis, proof of concept and in development).",
                "It is the portfolio's current activity: how much work is open and in which stage it piles up.",
                "document 20"),
    },
    "emb-ganados": {
        "es": t("Ganados: en uso",
                "Casos que están ahora en producción y, aparte, cuántos llegaron alguna vez a producción (incluidos los que se desengancharon después).",
                "Llegar a producción es el resultado que importa del embudo: solo lo que está en uso puede producir valor.",
                "documento 14"),
        "en": t("Won: in use",
                "Cases currently in production and, separately, how many ever reached production (including those disengaged later).",
                "Reaching production is the outcome that matters in the funnel: only what is in use can produce value.",
                "document 14"),
    },
    "emb-perdidos": {
        "es": t("Perdidos",
                "Casos que salieron del embudo, por salida: no aprobados, descartados y desenganchados después de estar en uso.",
                "Parar a tiempo es un resultado, no un fracaso: cada caso perdido con su motivo es aprendizaje de la organización y dinero que deja de gastarse.",
                "documento 21",
                "No aprobado: se paró en las fases 0–1. Descartado: se paró entre la hipótesis de valor y el desarrollo. Desenganchado: se retiró después de estar en uso."),
        "en": t("Lost",
                "Cases that left the funnel, by exit: not approved, discarded and disengaged after being in use.",
                "Stopping in time is an outcome, not a failure: each lost case with its reason is organisational learning and money no longer spent.",
                "document 21",
                "Not approved: stopped in phases 0–1. Discarded: stopped between value hypothesis and development. Disengaged: withdrawn after being in use."),
    },
    "emb-conversion": {
        "es": t("Conversión a producción",
                "Casos que llegaron a producción divididos por la suma de esos casos y los que se perdieron antes de llegar. Si los datos no incluyen casos no aprobados ni descartados, no se puede medir.",
                "Una conversión muy alta puede indicar que no se para nada; una muy baja, que se abren demasiados casos sin hipótesis de valor. Las dos piden revisar los criterios de las puertas.",
                "documento 21"),
        "en": t("Conversion to production",
                "Cases that reached production divided by the sum of those cases and the ones lost before getting there. If the data do not include cases not approved or discarded, it cannot be measured.",
                "A very high conversion may mean nothing is being stopped; a very low one, that too many cases are opened without a value hypothesis. Both call for reviewing the gate criteria.",
                "document 21"),
    },
    "emb-atascados": {
        "es": t("Casos atascados",
                "Casos que superan el límite de días de su estado (en rojo) o que se acercan a él (en amarillo). Los límites están en el JSON general de configuración.",
                "Un caso atascado consume recursos sin decisión. Pide que alguien decida: continuar, iterar, pivotar o parar.",
                "documento 20 y documento 21",
                "El primer número son los casos fuera de plazo; el segundo («+ n»), los que están cerca del límite."),
        "en": t("Stuck cases",
                "Cases over the day limit of their status (red) or close to it (amber). The limits are in the general configuration JSON.",
                "A stuck case consumes resources without a decision. It calls for someone to decide: continue, iterate, pivot or stop.",
                "document 20 and document 21",
                "The first number is the overdue cases; the second («+ n»), those close to the limit."),
    },
    "embudo": {
        "es": t("Embudo de casos de uso",
                "Los casos al vuelo por etapa (propuesto, hipótesis de valor, prueba de concepto, en desarrollo). A la derecha de cada etapa, los casos que no la superaron, con su motivo y lo aprendido; debajo, los que ya están en uso y los desenganchados. Al pulsar una etapa o una salida se ven sus casos.",
                "Gestiona la cartera como un embudo comercial: muestra dónde se acumulan y dónde se pierden los casos, y por qué. Así el consejo ve si las puertas filtran de verdad y qué ha aprendido la organización de lo que no salió.",
                "documento 00 §4.3 y documento 14",
                "Anchura de cada etapa: casos que la alcanzaron. Número dentro: casos que están ahora en ella. Cifras junto a cada etapa: eficiencias, retorno y coste de sus casos («prev.» = previstas, aún no realizadas). Tarjeta verde: en uso; tarjetas rojas: perdidos. «Sin motivo registrado» en rojo significa que falta pedirlo."),
        "en": t("Use-case funnel",
                "Cases in flight by stage (proposed, value hypothesis, proof of concept, in development). To the right of each stage, the cases that did not pass it, with their reason and what was learned; below, those already in use and those disengaged. Clicking a stage or an exit shows its cases.",
                "It manages the portfolio like a sales funnel: it shows where cases pile up and where they are lost, and why. The board sees whether the gates really filter and what the organisation has learned from what did not work out.",
                "document 00 §4.3 and document 14",
                "Width of each stage: cases that reached it. Number inside: cases in it now. Figures next to each stage: efficiencies, return and cost of its cases («prev.» = expected, not yet realised). Green card: in use; red cards: lost. «No reason recorded» in red means it still has to be requested."),
    },
    "embudo-det": {
        "es": t("Casos de una etapa",
                "Los casos de la etapa o la salida que se haya pulsado en el embudo: días en la etapa frente a su límite y desviación frente a la media o la mediana del estado; en las salidas, el motivo y las cifras que tenía el caso al salir.",
                "Identifica qué casos concretos están atascados o por qué se perdieron, y a quién hay que pedir una decisión.",
                "documento 20",
                "Filas en amarillo o rojo: cerca del límite o fuera de plazo. Los botones Mediana/Media eligen con qué se compara."),
        "en": t("Cases in a stage",
                "The cases of the stage or exit clicked in the funnel: days in the stage against its limit and deviation from the status mean or median; for exits, the reason and the figures the case had when it left.",
                "It identifies which specific cases are stuck or why they were lost, and whom to ask for a decision.",
                "document 20",
                "Amber or red rows: close to the limit or overdue. The Median/Mean buttons choose the comparison."),
        "columnas": ["Caso", "Compañía", "Tecnología", "Complejidad", "En la etapa desde", "Días", "Límite", "% del límite", "Desviación …", "Plazo", "Salió desde", "Fecha de salida", "Días en el embudo", "Eficiencias", "Retorno", "Coste anual", "Inversión", "Motivo"],
    },
    "embudo-preg": {
        "es": t("Preguntas sobre los tiempos",
                "Respuestas, con los casos filtrados, a preguntas sobre el historial de estados: cuánto se está en cada estado, cuánto se tarda de uno a otro, si cambia según el tipo de caso, qué casos se atascan y cuántas entradas, ganados y perdidos hay por trimestre.",
                "Convierte el historial en aprendizaje: qué tipo de caso tarda más y en qué etapa conviene simplificar el proceso o reforzarlo.",
                "documento 14",
                "Elija la pregunta en el desplegable; la tabla cambia con ella. Los tiempos solo cuentan los casos con fechas de cambio de estado."),
        "en": t("Questions about times",
                "Answers, using the filtered cases, to questions about the status history: how long cases stay in each status, how long it takes to go from one to another, whether it changes by type of case, which cases get stuck and how many entries, wins and losses there are per quarter.",
                "It turns the history into learning: which type of case takes longest and in which stage the process should be simplified or reinforced.",
                "document 14",
                "Choose the question in the drop-down; the table changes with it. Times only count cases with status-change dates."),
        "columnas": ["Estado", "Estancias", "Media", "Mediana", "P25 – P75", "Mín – máx", "Límite", "Superan el límite", "Ahora en el estado", "Frente a la mediana", "Grupo", "Con fechas", "Frente a la mediana total", "% del límite", "Trimestre", "Entradas", "Ganados (a producción)", "Perdidos", "Saldo en curso"],
    },
    # ---- Histórico y adopción
    "hist": {
        "es": t("Histórico y tendencia",
                "Las fotos guardadas al cierre de cada sesión: evolución de eficiencias, retorno, coste y neto; casos nuevos, retirados y cambios de estado frente a la foto elegida; y puestas en producción por año.",
                "El consejo decide mejor con tendencias que con fotos sueltas. Comparar con la sesión anterior muestra si se cumplió lo previsto y qué ha cambiado desde entonces.",
                "documento 60",
                "Elija la foto con la que comparar en «Comparar con» de la barra superior. En las puestas en producción por año, la parte clara son años estimados."),
        "en": t("History and trend",
                "Snapshots saved at the close of each session: evolution of efficiencies, return, cost and net; new, withdrawn and status-changed cases against the chosen snapshot; and go-lives per year.",
                "The board decides better with trends than with isolated snapshots. Comparing with the previous session shows whether what was planned happened and what has changed since.",
                "document 60",
                "Choose the snapshot to compare with in «Compare with» in the top bar. In go-lives per year, the light part is estimated years."),
        "columnas": ["Foto", "Casos", "En uso", "Eficiencias", "Retorno", "Coste anual", "Neto anual", "Neto potencial", "Movimiento", "Caso", "Detalle"],
    },
    "adop": {
        "es": t("Adopción y capacidad",
                "Licencias activas sobre asignadas, uso de la plataforma de agentes, usos de IA fuera de los canales aprobados (shadow AI) y controles técnicos frente a ellos, cobertura de la formación obligatoria, vacantes clave y rotación del equipo.",
                "La IA que no se usa no genera valor, y la que se usa fuera de los canales aprobados genera riesgo. La formación es además una obligación del Reglamento de IA (alfabetización).",
                "documento 23 (adopción y cambio), documento 31 (uso aceptable) y documento 50 (personas)"),
        "en": t("Adoption and capability",
                "Active over assigned licences, use of the agent platform, uses of AI outside approved channels (shadow AI) and technical controls against them, coverage of mandatory training, key vacancies and team turnover.",
                "AI that is not used creates no value, and AI used outside approved channels creates risk. Training is also an obligation under the AI Act (AI literacy).",
                "document 23 (adoption and change), document 31 (acceptable use) and document 50 (people)"),
        "columnas": ["Copilot · licencias activas", "Claude · licencias activas", "Plataforma agéntica", "Shadow AI detectada", "Controles técnicos frente al shadow AI", "Formación", "Vacantes clave", "Rotación del equipo"],
    },
    # ---- Riesgo y cumplimiento
    "rie1": {
        "es": t("Semáforo regulatorio",
                "Casos por nivel del Reglamento de IA según la clasificación de la compañía y según la estimación del consejo asesor, y la cobertura de cada control.",
                "Las discrepancias entre las dos clasificaciones y los controles pendientes señalan dónde puede haber obligaciones sin cubrir antes de que las descubra un supervisor.",
                "documento 32, documento 33 y documento 34",
                "Si las dos columnas no coinciden en «alto riesgo», hay que pedir criterio jurídico. En las barras de controles: verde hecho, amarillo pendiente, gris no aplica, vacío sin dato."),
        "en": t("Regulatory traffic light",
                "Cases by AI Act level according to the company's classification and to the advisory board's estimate, and the coverage of each control.",
                "Discrepancies between the two classifications and pending controls show where obligations may be uncovered before a supervisor finds them.",
                "document 32, document 33 and document 34",
                "If the two columns do not match on «high risk», legal advice is needed. In the control bars: green done, amber pending, grey not applicable, blank no data."),
        "columnas": ["Nivel", propia("Compañía", "Casos clasificados así por la compañía, con criterio jurídico.", "Company", "Cases classified this way by the company, with legal criteria."), "Estimación …",
                     propia("RIA", "Clasificación del caso según el Reglamento (UE) de Inteligencia Artificial.", "RIA (AI Act)", "Classification of the case under the EU Artificial Intelligence Act."),
                     propia("FRIA", "Evaluación de impacto en los derechos fundamentales; obligatoria para ciertos usos de alto riesgo.", "FRIA", "Fundamental rights impact assessment; mandatory for certain high-risk uses."),
                     propia("DPIA", "Evaluación de impacto en protección de datos (RGPD), cuando el tratamiento de datos personales entraña alto riesgo.", "DPIA", "Data protection impact assessment (GDPR), when processing personal data involves high risk."),
                     propia("Seguridad", "Diseño y pruebas de seguridad del sistema de IA.", "Security", "Security design and testing of the AI system."),
                     propia("MUC", "Manual de uso y control: instrucciones de uso, supervisión humana y límites del sistema.", "MUC (user and control manual)", "User and control manual: instructions for use, human oversight and limits of the system."),
                     propia("Riesgo de IA ofensiva", "Análisis del riesgo de que el caso sea atacado con IA (agentes atacantes, inyección de instrucciones).", "Offensive-AI risk", "Analysis of the risk of the case being attacked with AI (attacking agents, prompt injection)."),
                     propia("hecho · pendiente · no aplica · sin dato", "Número de casos en cada situación para ese control.", "done · pending · not applicable · no data", "Number of cases in each situation for that control.")],
    },
    "rie2": {
        "es": t("Incidentes de IA y brechas de datos",
                "Incidentes del periodo por tipo y origen (agente atacante, agente propio manipulado, proveedor), horas hasta detectar, contener y resolver frente al objetivo de recuperación, brechas de datos personales y si se notificaron a la autoridad en 72 horas.",
                "Los incidentes son la prueba real de que los controles funcionan. El plazo de 72 horas del RGPD es una obligación legal con sanción.",
                "documento 37 (no conformidades e incidentes)"),
        "en": t("AI incidents and data breaches",
                "Incidents in the period by type and origin (attacking agent, own agent manipulated, supplier), hours to detect, contain and resolve against the recovery objective, personal data breaches and whether they were notified to the authority within 72 hours.",
                "Incidents are the real proof that controls work. The GDPR 72-hour deadline is a legal obligation with sanctions.",
                "document 37 (non-conformities and incidents)"),
        "columnas": ["Fecha", "Caso", propia("Tipo", "Deriva (el modelo empeora), error, caída o seguridad.", "Type", "Drift (the model degrades), error, outage or security."), "Origen", "Descripción", "Detectar / contener / resolver", "Brecha de datos", "AEPD (72 h)", "DORA"],
    },
    "rie3": {
        "es": t("Guardarraíles y operación de los asistentes",
                "Para los asistentes generativos y los agentes: contención (consultas resueltas sin persona), derivación a una persona, activación de los guardarraíles, revisión humana de calidad y fechas de la última evaluación y de las pruebas adversarias (red teaming).",
                "Muestra si los asistentes resuelven lo que prometen y si están protegidos. Un asistente en uso sin pruebas adversarias es un riesgo sin evaluar.",
                "documento 35 y documento 52 (operación)"),
        "en": t("Guardrails and assistant operations",
                "For generative assistants and agents: containment (queries resolved without a person), hand-over to a person, guardrail activations, human quality review and dates of the last evaluation and of adversarial testing (red teaming).",
                "It shows whether assistants deliver what they promise and whether they are protected. An assistant in use without adversarial testing is an unassessed risk.",
                "document 35 and document 52 (operations)"),
        "columnas": ["Caso", "Estado", "Contención", "Derivación", "Guardarraíl", "QA humano", "Evals", "Red teaming"],
    },
    "iaof": {
        "es": t("Exposición a ataques con IA",
                "Doble factor en las aplicaciones expuestas, vulnerabilidades críticas abiertas, horas hasta detectar y contener, identidades de agentes con permisos excesivos, agentes que escriben o pagan sin validación humana, brechas y preparación (pruebas de intrusión, simulacros y procedimiento de respuesta).",
                "Los atacantes ya usan agentes que operan a velocidad de máquina. El consejo debe saber si la compañía detecta y contiene a esa velocidad, y qué le falta para hacerlo.",
                "documento 35 (seguridad de IA y agentes)",
                "La primera fila son indicadores de exposición (cuanto más bajo, mejor, salvo el doble factor); la segunda, la preparación. «Sin dato» significa que la compañía no lo ha reportado, no que sea cero."),
        "en": t("Exposure to AI-driven attacks",
                "MFA on exposed applications, open critical vulnerabilities, hours to detect and contain, agent identities with excessive permissions, agents that write or pay without human validation, breaches and preparedness (penetration tests, drills and response procedure).",
                "Attackers already use agents operating at machine speed. The board must know whether the company detects and contains at that speed, and what it lacks to do so.",
                "document 35 (AI and agent security)",
                "The first row is exposure indicators (lower is better, except MFA); the second, preparedness. «No data» means the company has not reported it, not that it is zero."),
        "columnas": ["Doble factor en aplicaciones expuestas", "Vulnerabilidades críticas abiertas > 30 días", "Horas hasta detectar / contener", "Identidades de agentes con permisos excesivos", "Agentes que escriben o pagan sin validación humana", "Brechas de datos / notificadas en 72 h", "Prueba de intrusión con IA ofensiva", "Éxito de la inyección de instrucciones", "Tratamientos con riesgo de IA ofensiva analizado", "Acciones de agentes registradas", "Detección de tráfico automatizado", "Runbook de incidentes de IA", "Simulacro con agente atacante", "Ensayo de notificación en 72 h"],
    },
    "agt": {
        "es": t("Identidad, permisos e intención de los agentes",
                "Para cada agente: qué acciones puede ejecutar, con qué identidades y credenciales, si cumple el mínimo privilegio, cada cuánto rota sus claves, si un control externo al modelo autoriza cada acción, si hay validación humana, botón de parada, registro de acciones, prueba de inyección de instrucciones y si su proveedor está registrado.",
                "Un agente que actúa (autonomía A2 o A3) puede mover dinero, datos o sistemas. Sin mínimo privilegio y sin botón de parada, un error o una manipulación se convierte en un incidente.",
                "documento 35"),
        "en": t("Agent identity, permissions and intent",
                "For each agent: which actions it can run, with which identities and credentials, whether it meets least privilege, how often its keys rotate, whether a control outside the model authorises each action, whether there is human validation, a kill switch, action logging, a prompt-injection test and whether its supplier is registered.",
                "An agent that acts (autonomy A2 or A3) can move money, data or systems. Without least privilege and a kill switch, an error or a manipulation becomes an incident.",
                "document 35"),
        "columnas": ["Caso", "Estado", "Acciones", "Identidades · credenciales", "Mínimo privilegio", "Rotación", "Control de intención", "Validación humana", "Parada", "Registro de acciones", "Prueba de inyección", "Proveedor DORA"],
    },
    # ---- Inventario
    "inventario": {
        "es": t("Inventario por compañía y unidad",
                "Cada caso con su estado, sus cifras y sus etiquetas, agrupado por compañía y unidad o seguido, en tarjetas o en tabla. Al pulsar un caso se abre su ficha.",
                "Es el detalle que respalda todas las cifras agregadas del panel: cualquier importe se puede rastrear hasta los casos que lo forman.",
                "documento 32 y T01",
                "En la vista de tabla, pulse un encabezado para ordenar; pase el ratón por él para ver qué significa."),
        "en": t("Inventory by company and unit",
                "Each case with its status, figures and tags, grouped by company and unit or listed, as cards or as a table. Clicking a case opens its record.",
                "It is the detail behind every aggregate figure in the dashboard: any amount can be traced to the cases that make it up.",
                "document 32 and T01",
                "In the table view, click a header to sort; hover over it to see what it means."),
        "columnas": ["ID", "Caso", "Qué es y para qué se usa", "Compañía", "Unidad", "Estado", "Puesta en producción", "Tecnología", "Reglamento IA …", "Controles", "Días en el estado", "Límite (días)", "Plazo en el estado", "Construcción", "Coste anual", "Eficiencias", "Capacidad no materializada", "Retorno", "Neto anual", "Neto potencial", "Inversión adicional", "€ neto por € adicional", "Δ neto …", "Plazo del potencial", "Dato del valor"],
    },
    # ---- Panel móvil
    "m-resumen": {
        "es": t("Resumen",
                "Neto anual de la IA (retorno total menos costes) con su evolución entre fotos, retorno total, costes, valor validado (o inversión adicional, en potencial), casos con controles completos y casos por estado.",
                "Es la respuesta en treinta segundos: si la cartera aporta dinero, cuánto de ese valor está comprobado y si los casos tienen sus controles.",
                "documento 40"),
        "en": t("Summary",
                "Annual net of AI (total return minus costs) with its evolution across snapshots, total return, costs, validated value (or additional investment, in potential), cases with complete controls and cases by status.",
                "It is the thirty-second answer: whether the portfolio earns money, how much of that value is checked and whether cases have their controls.",
                "document 40"),
        "columnas": ["Neto anual", "Retorno total", "Costes", propia("Valor validado", "Porcentaje del valor actual comprobado por Control de Gestión.", "Validated value", "Share of current value checked by Management Control."), propia("Controles completos", "Casos con todos sus controles hechos o no aplicables.", "Complete controls", "Cases with all their controls done or not applicable.")],
    },
    "m-alertas": {
        "es": t("Alertas",
                "Lo que requiere atención del consejo, calculado con los datos del panel: valor sin validar, casos sin clasificar o sin controles completos por debajo de su umbral, dependencia de un solo caso, casos en uso con neto negativo, capacidad liberada sin materializar, brechas de datos sin notificar a tiempo y agentes sin ficha de permisos, entre otros.",
                "Resume lo que hay que preguntar en la sesión, sin tener que recorrer el panel completo.",
                "documento 61 (conversación con el consejo)",
                "Rojo: grave o fuera de umbral; amarillo: cerca del umbral; sin color: a tener en cuenta."),
        "en": t("Alerts",
                "What needs the board's attention, calculated from the dashboard data: unvalidated value, unclassified cases or incomplete controls below their threshold, dependence on a single case, cases in use with negative net, unmaterialised freed capacity, data breaches not notified on time and agents without a permissions record, among others.",
                "It summarises what to ask in the session without going through the full dashboard.",
                "document 61 (board conversation)",
                "Red: serious or beyond the threshold; amber: close to the threshold; no colour: worth noting."),
    },
    "m-embudo": {
        "es": t("Embudo de casos",
                "Casos ahora en cada etapa, cuántos la alcanzaron, mediana de días y casos atascados; debajo, los que están en uso y los que no pasaron o se desengancharon, con su motivo. Al pulsar una etapa se ven sus casos.",
                "Muestra dónde se acumulan y dónde se pierden los casos, y por qué: parar a tiempo es un resultado y forma parte del aprendizaje.",
                "documento 14",
                "La barra de cada etapa es la proporción de casos que la alcanzaron. «n fuera»: casos fuera de plazo. «prev.»: cifras previstas, aún no realizadas."),
        "en": t("Case funnel",
                "Cases now in each stage, how many reached it, median days and stuck cases; below, those in use and those that did not pass or were disengaged, with their reason. Tapping a stage shows its cases.",
                "It shows where cases pile up and where they are lost, and why: stopping in time is an outcome and part of learning.",
                "document 14",
                "Each stage's bar is the share of cases that reached it. «n overdue»: cases past their limit. «prev.»: expected figures, not yet realised."),
    },
    "m-top": {
        "es": t("Casos que más aportan",
                "Los cinco casos con mayor neto anual positivo (actual o potencial) y su variación frente a la foto elegida.",
                "Dice de qué casos depende el resultado de la cartera: son los que más conviene proteger, medir bien y, si procede, escalar.",
                "documento 43"),
        "en": t("Cases contributing most",
                "The five cases with the highest positive annual net (current or potential) and their change against the chosen snapshot.",
                "It shows which cases the portfolio's result depends on: those most worth protecting, measuring well and, where appropriate, scaling.",
                "document 43"),
    },
    "m-rinde": {
        "es": t("Dónde rinde más el siguiente euro",
                "Los cinco casos con más neto anual adicional por euro de inversión adicional, con la inversión, el neto que añadiría y el plazo.",
                "Ayuda a decidir dónde poner la siguiente inversión. Son cifras potenciales: dependen de las hipótesis de cada caso.",
                "documento 14 y documento 40",
                "«x € por €»: euros de neto anual adicional por euro invertido. Debajo: inversión → neto anual que añade."),
        "en": t("Where the next euro pays off most",
                "The five cases with the most additional annual net per euro of additional investment, with the investment, the net it would add and the timeframe.",
                "It helps decide where to put the next investment. These are potential figures: they depend on each case's hypotheses.",
                "document 14 and document 40",
                "«x € per €»: euros of additional annual net per euro invested. Below: investment → annual net it adds."),
    },
    "m-novedades": {
        "es": t("Novedades",
                "Casos nuevos, puestos en producción, retirados o con cambio de estado desde la foto elegida.",
                "Es lo que ha cambiado desde la última sesión: lo primero que el consejo querrá saber.",
                "documento 60"),
        "en": t("What's new",
                "Cases that are new, went into production, were withdrawn or changed status since the chosen snapshot.",
                "It is what has changed since the last session: the first thing the board will want to know.",
                "document 60"),
    },
}
# el panel móvil reutiliza las tarjetas de transversales y madurez del completo (mismas claves)
